 Sat, 05 Oct 2019 16:25:42  INFO remote_connection.py __init__ [ line:117 ] Could not connect to port 4723 on host 127.0.0.1
 Sat, 05 Oct 2019 16:25:42  INFO remote_connection.py __init__ [ line:136 ] Could not get IP address for host: 127.0.0.1
 Sat, 05 Oct 2019 16:25:43  WARNING connectionpool.py urlopen [ line:665 ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A50F7D90B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
 Sat, 05 Oct 2019 16:25:44  WARNING connectionpool.py urlopen [ line:665 ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A50F7F50B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
 Sat, 05 Oct 2019 16:25:45  WARNING connectionpool.py urlopen [ line:665 ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A50F7F5550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
 Sat, 05 Oct 2019 16:25:48  INFO remote_connection.py __init__ [ line:117 ] Could not connect to port 4723 on host 127.0.0.1
 Sat, 05 Oct 2019 16:25:48  INFO remote_connection.py __init__ [ line:136 ] Could not get IP address for host: 127.0.0.1
 Sat, 05 Oct 2019 16:25:49  WARNING connectionpool.py urlopen [ line:665 ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A50FB25B38>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
 Sat, 05 Oct 2019 16:25:50  WARNING connectionpool.py urlopen [ line:665 ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A50FB25DD8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
 Sat, 05 Oct 2019 16:25:51  WARNING connectionpool.py urlopen [ line:665 ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A50FB25B70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
 Sat, 05 Oct 2019 16:25:53  INFO remote_connection.py __init__ [ line:117 ] Could not connect to port 4723 on host 127.0.0.1
 Sat, 05 Oct 2019 16:25:53  INFO remote_connection.py __init__ [ line:136 ] Could not get IP address for host: 127.0.0.1
 Sat, 05 Oct 2019 16:25:54  WARNING connectionpool.py urlopen [ line:665 ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A50FB2E358>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
 Sat, 05 Oct 2019 16:25:55  WARNING connectionpool.py urlopen [ line:665 ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A50FB2E400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
 Sat, 05 Oct 2019 16:25:56  WARNING connectionpool.py urlopen [ line:665 ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A50FB2E828>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
