{"name": "test_scan_0_success[data0]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <test_cases.test_login.TestLogin object at 0x000002B662C90D30>\ndata = {'pwd': '123456', 'user': '15533366622'}\nrun_app = <appium.webdriver.webdriver.WebDriver (session=\"9bc46a7c-2eb2-4683-b4b1-6151be5eaae1\")>\n\n    @pytest.mark.parametrize(\"data\", ld.success_data)\n    def test_scan_0_success(self, data, run_app):\n        # 执行登录\n>       LoginPage(run_app).login_action(data[\"user\"], data[\"pwd\"])\n\ntest_cases\\test_login.py:81: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage_ojbects\\login_page.py:25: in login_action\n    self.wait_ele_visible(Loc.user_loc, \"登录页_等待用户名元素可见\")\ncommon\\basepage.py:31: in wait_ele_visible\n    WebDriverWait(self.driver, timeout, frequency).until(ec.visibility_of_element_located(loc))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"9bc46a7c-2eb2-4683-b4b1-6151be5eaae1\")>\nmethod = <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x000002B662CD1CF8>\nmessage = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException"}, "attachments": [{"name": "log", "source": "466e2ff1-e3e6-4a98-97d7-894a5e456126-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '15533366622', 'pwd': '123456'}"}], "start": 1570346386575, "stop": 1570346418788, "uuid": "59e4a427-fe6b-4ef9-a2d0-b0bf04334b62", "historyId": "f552efed59dc39938bde8ff222775e8a", "testCaseId": "81839c0cbe35567b8c59ea7f3b8a85c7", "fullName": "test_cases.test_login.TestLogin#test_scan_0_success", "labels": [{"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-HH83IEE"}, {"name": "thread", "value": "22392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login"}]}