{"name": "test_login_3_wrong_data[data1]", "status": "passed", "attachments": [{"name": "log", "source": "be5d331e-cd97-4d02-b769-94124980843e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '13072721099', 'pwd': '123456', 'check': '账号不存在或者密码有误'}"}], "start": 1570293999830, "stop": 1570294011019, "uuid": "76440425-f420-4df0-ab4b-13ff31e1886a", "historyId": "d7022cb4a99f936afa4bb5e8c31ae3b4", "testCaseId": "e14d7f91890c6cf063c524fafe021747", "fullName": "test_cases.test_login.TestLogin#test_login_3_wrong_data", "labels": [{"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-HH83IEE"}, {"name": "thread", "value": "2168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login"}]}