{"name": "test_login_3_wrong_data[data0]", "status": "passed", "attachments": [{"name": "log", "source": "057193cb-a1da-4ea0-9bfa-9da9e740ca05-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '13072721092', 'pwd': '12345', 'check': '账号不存在或者密码有误'}"}], "start": 1570293974655, "stop": 1570293985170, "uuid": "051d2efa-20cf-4c42-b701-792312d3b1e9", "historyId": "2270eae33eb6701373c952af6dd5d846", "testCaseId": "e14d7f91890c6cf063c524fafe021747", "fullName": "test_cases.test_login.TestLogin#test_login_3_wrong_data", "labels": [{"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-HH83IEE"}, {"name": "thread", "value": "2168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_login"}]}